name: pocket_gpt
description: A pocket-sized GPT assistant
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  dart_openai: ^1.8.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  go_router: ^6.2.0
  bubble: ^1.2.1
  equatable: ^2.0.5
  uuid: ^4.0.0-beta1-1
  provider: ^6.0.5
  flutter_markdown:
    path: ../packages/packages/flutter_markdown
  flutter_highlighter: ^0.1.1
  google_fonts: ^4.0.3
  markdown: ^7.0.1
  highlighter: ^0.1.1
  url_launcher: ^6.1.10
  system_tray: ^0.1.1
  window_manager: ^0.3.1
  screen_retriever: ^0.1.6
  json_annotation: ^4.8.0
  package_info_plus: ^3.0.3
  pub_semver: ^2.1.3
  http: ^0.13.5
  url_strategy: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  extra_pedantic: ^3.0.0
  json_serializable: ^6.6.1

flutter:
  uses-material-design: true
  assets:
    - assets/app_icon.png
    - assets/app_icon.ico
    - assets/app_logo.png
    - assets/discord_256x.png
    - assets/twitter_256x.png
    - assets/linked_in_256x.png
    - assets/github_black_256x.png
    - assets/github_white_256x.png
    - assets/profile_256x.png